### ISSUE TITLE
Tracking issue: lnprototest integration

### ISSUE THREAD

**Issue by vincenzopalazzo** [vincenzopalazzo/lampo.rs#38]
In order to integrate lnprototest we need to add the following information just 
for the init message

- [x] Support for bitcoin core https://github.com/dart-lightning/lampo.rs/issues/39
- [x] Support for setting up the private and public key in Lampo https://github.com/dart-lightning/lampo.rs/issues/40
- [x] Adding bitcoin core in lampo lnprototest https://github.com/dart-lightning/lampo.rs/issues/41
- [ ] Integrate lnprototest test inside the CI
